### ISSUE TITLE
Connection Handling - Best Practice

### ISSUE THREAD

**Issue by elsbiet** [KonnexionsGmbH/oranif#23]
Facing growing number of connections to the database.

My approach:

% connect:
%..
    Context = dpi:context_create(?DPI_MAJOR_VERSION, ?DPI_MINOR_VERSION),
    Connection = dpi:conn_create(               
                   Context, User, Password, Tns,
                   #{encoding => Encoding, nencoding => Nencoding}, #{}
                  ),  

%..

%disconnect
    ok = dpi:conn_close(Connection, [], <<>>),
    ok = dpi:context_destroy(Context),

%

repeated execution of the above code leads to to a strictly monotonic growing number of database connections.

is there anything i missed?

thanks in advance for your asnwer.

my environmend:

os = debian 11
db: Oracle Database 18c Express Edition Release 18.0.0.0.0
erlang: otp24

**Comment by c-bik** [comment]
Hi @elsbiet,

Great to know that you are using our driver.

Can you please provide some insight as to how are you finding out connection count?

I suspect, that Oracle holds on to a connection as long as the TCP socket is still in TIME_WAIT.

Alternatively, if you would like to keep connection count under control I hope using a connection pool instead with some max connection limit might help.

TIA

**Comment by elsbiet** [comment]
hi and thanks for your answer.

indeed my testing was a bit too brutal. after inserting a one second sleep after closing a connection and before opening the next connection everything works fine. the oracle server seems to need some time to completely shut down and cleanup a connection.

elsbiet
